require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrgtreesController do

  # This should return the minimal set of attributes required to create a valid
  # Orgtree. As you add validations to Orgtree, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "parent" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgtreesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all orgtrees as @orgtrees" do
      orgtree = Orgtree.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orgtrees).should eq([orgtree])
    end
  end

  describe "GET show" do
    it "assigns the requested orgtree as @orgtree" do
      orgtree = Orgtree.create! valid_attributes
      get :show, {:id => orgtree.to_param}, valid_session
      assigns(:orgtree).should eq(orgtree)
    end
  end

  describe "GET new" do
    it "assigns a new orgtree as @orgtree" do
      get :new, {}, valid_session
      assigns(:orgtree).should be_a_new(Orgtree)
    end
  end

  describe "GET edit" do
    it "assigns the requested orgtree as @orgtree" do
      orgtree = Orgtree.create! valid_attributes
      get :edit, {:id => orgtree.to_param}, valid_session
      assigns(:orgtree).should eq(orgtree)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orgtree" do
        expect {
          post :create, {:orgtree => valid_attributes}, valid_session
        }.to change(Orgtree, :count).by(1)
      end

      it "assigns a newly created orgtree as @orgtree" do
        post :create, {:orgtree => valid_attributes}, valid_session
        assigns(:orgtree).should be_a(Orgtree)
        assigns(:orgtree).should be_persisted
      end

      it "redirects to the created orgtree" do
        post :create, {:orgtree => valid_attributes}, valid_session
        response.should redirect_to(Orgtree.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orgtree as @orgtree" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgtree.any_instance.stub(:save).and_return(false)
        post :create, {:orgtree => { "parent" => "invalid value" }}, valid_session
        assigns(:orgtree).should be_a_new(Orgtree)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orgtree.any_instance.stub(:save).and_return(false)
        post :create, {:orgtree => { "parent" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orgtree" do
        orgtree = Orgtree.create! valid_attributes
        # Assuming there are no other orgtrees in the database, this
        # specifies that the Orgtree created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Orgtree.any_instance.should_receive(:update_attributes).with({ "parent" => "1" })
        put :update, {:id => orgtree.to_param, :orgtree => { "parent" => "1" }}, valid_session
      end

      it "assigns the requested orgtree as @orgtree" do
        orgtree = Orgtree.create! valid_attributes
        put :update, {:id => orgtree.to_param, :orgtree => valid_attributes}, valid_session
        assigns(:orgtree).should eq(orgtree)
      end

      it "redirects to the orgtree" do
        orgtree = Orgtree.create! valid_attributes
        put :update, {:id => orgtree.to_param, :orgtree => valid_attributes}, valid_session
        response.should redirect_to(orgtree)
      end
    end

    describe "with invalid params" do
      it "assigns the orgtree as @orgtree" do
        orgtree = Orgtree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgtree.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgtree.to_param, :orgtree => { "parent" => "invalid value" }}, valid_session
        assigns(:orgtree).should eq(orgtree)
      end

      it "re-renders the 'edit' template" do
        orgtree = Orgtree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orgtree.any_instance.stub(:save).and_return(false)
        put :update, {:id => orgtree.to_param, :orgtree => { "parent" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orgtree" do
      orgtree = Orgtree.create! valid_attributes
      expect {
        delete :destroy, {:id => orgtree.to_param}, valid_session
      }.to change(Orgtree, :count).by(-1)
    end

    it "redirects to the orgtrees list" do
      orgtree = Orgtree.create! valid_attributes
      delete :destroy, {:id => orgtree.to_param}, valid_session
      response.should redirect_to(orgtrees_url)
    end
  end

end
